In [1]:
!head /Users/sr320/Desktop/oly/20181127_oly_genome_snap02.all.noseqs.sorted.gff

##gff-version 3
Contig0	.	contig	1	116746	.	.	.	ID=Contig0;Name=Contig0
Contig0	repeatmasker	match	1	213	1074	+	.	ID=Contig0:hit:44:1.3.0.0;Name=species:Helitron-N2f_CGi|genus:RC%2FHelitron;Target=species:Helitron-N2f_CGi|genus:RC%2FHelitron 1 209 +
Contig0	repeatmasker	match_part	1	213	1074	+	.	ID=Contig0:hsp:44:1.3.0.0;Parent=Contig0:hit:44:1.3.0.0;Target=species:Helitron-N2f_CGi|genus:RC%252FHelitron 1 209 +
Contig0	repeatmasker	match	264	306	397	+	.	ID=Contig0:hit:45:1.3.0.0;Name=species:rnd-1_family-144|genus:Unknown;Target=species:rnd-1_family-144|genus:Unknown 296 338 +
Contig0	repeatmasker	match_part	264	306	397	+	.	ID=Contig0:hsp:45:1.3.0.0;Parent=Contig0:hit:45:1.3.0.0;Target=species:rnd-1_family-144|genus:Unknown 296 338 +
Contig0	repeatmasker	match	357	411	318	+	.	ID=Contig0:hit:46:1.3.0.0;Name=species:BivaMD-SINE1_CrVi|genus:SINE%2FtRNA;Target=species:BivaMD-SINE1_CrVi|genus:SINE%2FtRNA 182 236 +
Contig0	repeatmasker	match_part	357	411	318	+	.	ID=Contig0:hsp:46:1.3.0.0;Par

In [2]:
!cat /Users/sr320/Desktop/oly/20181127_oly_genome_snap02.all.noseqs.sorted.gff | awk '{print $2}' | sort | uniq

.
3
blastn
blastx
est2genome
maker
protein2genome
repeatmasker
repeatrunner
snap_masked


In [3]:
!fgrep "maker" /Users/sr320/Desktop/oly/20181127_oly_genome_snap02.all.noseqs.sorted.gff | head

Contig0	maker	gene	12485	93036	.	+	.	ID=maker-Contig0-snap-gene-0.6;Name=maker-Contig0-snap-gene-0.6
Contig0	maker	mRNA	12485	93036	.	+	.	ID=maker-Contig0-snap-gene-0.6-mRNA-1;Parent=maker-Contig0-snap-gene-0.6;Name=maker-Contig0-snap-gene-0.6-mRNA-1;_AED=0.17;_eAED=0.17;_QI=337|0.75|0.76|1|0.51|0.64|42|467|1560
Contig0	maker	exon	12485	12571	.	+	.	ID=maker-Contig0-snap-gene-0.6-mRNA-1:exon:12;Parent=maker-Contig0-snap-gene-0.6-mRNA-1
Contig0	maker	five_prime_UTR	12485	12571	.	+	.	ID=maker-Contig0-snap-gene-0.6-mRNA-1:five_prime_utr;Parent=maker-Contig0-snap-gene-0.6-mRNA-1
Contig0	maker	exon	13175	13233	.	+	.	ID=maker-Contig0-snap-gene-0.6-mRNA-1:exon:13;Parent=maker-Contig0-snap-gene-0.6-mRNA-1
Contig0	maker	five_prime_UTR	13175	13233	.	+	.	ID=maker-Contig0-snap-gene-0.6-mRNA-1:five_prime_utr;Parent=maker-Contig0-snap-gene-0.6-mRNA-1
Contig0	maker	exon	16209	16373	.	+	.	ID=maker-Contig0-snap-gene-0.6-mRNA-1:exon:14;Parent=maker-Contig0-snap-gene-0.6-mRNA-1
Contig0	maker	five_prime_UT

In [5]:
!fgrep "maker" /Users/sr320/Desktop/oly/20181127_oly_genome_snap02.all.noseqs.sorted.gff \
| awk '{print $3}' | sort | uniq -c

139671 CDS
142530 exon
9468 five_prime_UTR
24680 gene
24680 mRNA
6598 three_prime_UTR


In [7]:
!fgrep "maker" /Users/sr320/Desktop/oly/20181127_oly_genome_snap02.all.noseqs.sorted.gff > \
/Users/sr320/Desktop/oly/20181127_oly_genome_snap02.all.noseqs.sorted.maker.gff

In [11]:
!head /Users/sr320/Desktop/oly/20181127_oly_genome_snap02.all.noseqs.sorted.maker.gff

Contig0	maker	gene	12485	93036	.	+	.	ID=maker-Contig0-snap-gene-0.6;Name=maker-Contig0-snap-gene-0.6
Contig0	maker	mRNA	12485	93036	.	+	.	ID=maker-Contig0-snap-gene-0.6-mRNA-1;Parent=maker-Contig0-snap-gene-0.6;Name=maker-Contig0-snap-gene-0.6-mRNA-1;_AED=0.17;_eAED=0.17;_QI=337|0.75|0.76|1|0.51|0.64|42|467|1560
Contig0	maker	exon	12485	12571	.	+	.	ID=maker-Contig0-snap-gene-0.6-mRNA-1:exon:12;Parent=maker-Contig0-snap-gene-0.6-mRNA-1
Contig0	maker	five_prime_UTR	12485	12571	.	+	.	ID=maker-Contig0-snap-gene-0.6-mRNA-1:five_prime_utr;Parent=maker-Contig0-snap-gene-0.6-mRNA-1
Contig0	maker	exon	13175	13233	.	+	.	ID=maker-Contig0-snap-gene-0.6-mRNA-1:exon:13;Parent=maker-Contig0-snap-gene-0.6-mRNA-1
Contig0	maker	five_prime_UTR	13175	13233	.	+	.	ID=maker-Contig0-snap-gene-0.6-mRNA-1:five_prime_utr;Parent=maker-Contig0-snap-gene-0.6-mRNA-1
Contig0	maker	exon	16209	16373	.	+	.	ID=maker-Contig0-snap-gene-0.6-mRNA-1:exon:14;Parent=maker-Contig0-snap-gene-0.6-mRNA-1
Contig0	maker	five_prime_UT

## post issue
```
Issue
How do we get Swiss-Prot protein match for maker gff file.
Specifically 
Contig0	maker	gene	12485	93036	.	+	.	ID=maker-Contig0-snap-gene-0.6;Name=maker-Contig0-snap-gene-0.6
```

In [13]:
!fgrep "maker	gene" /Users/sr320/Desktop/oly/20181127_oly_genome_snap02.all.noseqs.sorted.maker.gff \
> /Users/sr320/Desktop/oly/20181127_oly_genome_snap02.all.noseqs.sorted.maker-gene.gff

In [15]:
!wc -l /Users/sr320/Desktop/oly/20181127_oly_genome_snap02.all.noseqs.sorted.maker-gene.gff

   24680 /Users/sr320/Desktop/oly/20181127_oly_genome_snap02.all.noseqs.sorted.maker-gene.gff
